apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ideaboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ideaboard-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@db.ideaboard.svc.cluster.local:5432/ideaboard?schema=public"
            - name: CORS_ORIGIN
              value: "http://localhost:3000"
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ideaboard
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000
