apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ideaboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ideaboard-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://backend.ideaboard.svc.cluster.local:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ideaboard
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
