apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ideaboard-ingress
  namespace: ideaboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: your-domain.com
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
  tls:
    - hosts:
        - your-domain.com
      secretName: ideaboard-tls  # create via cert-manager or manually
